language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: BteS7L9bis5GLVU8wWTp+HRP2OinfL/wQg6UKbUtluvT7Ztru1YaQ5MG+6njMEMn+LWRJ1dnFW+PlqBPi4VvxdKeJx33ev7mkjNXS5aLQqmhrtnVTZC7lYU8Una9h628a/aim9mYDvhUAkzL2VUywbMTK7ljZ3oTHL13nK3tIXmsGWPgoUs0WJEEzJB3Q45Y5Y47wIClTFLFitl69uYbJrD0tMZD7U1D3phPYVJphFv42U0MeYVSbkIWF6k2C1Fh0KizXnRjYIO4Ndvq/UdlsjTel7hG8WkwYfmHrKYu/hv/DU3ZFi3vEJkxKRnWtZdTfj60JPEE0AhfwrZcT9aAhzk6LwktsBVfjQTgrxrsW5akjGlKwXBN+CWexU5VVo7nQ2IqYWFiZ269OZKL8/oy3NCi3Qj2Cs+op2WlI20PUBDU/Yd/GSEA6WC1b+CWXCIJI4riTqC5OANeOaoDr1OXbgoMgCYiXqzbElnMZh0v1EqmMoiw9SO30LxXOYdrECcY3t/mwqupSCoPNlcFVGpB8HORTJbMUqZP/JpbfJGZheu/hkBxW0wK5OM7MsgbUOYukm676PkMxJc8ERDeaCnwGwhwHKRhJBDmfKMWi1CMoiYlvVdnBowwB5wcm8TsVveoDfMuLf659Pprn+hWpk2voR8TNNpZT1bmdjU0Q2ZPXUc=
  app: aqueous-shore-55408
  on:
    repo: dermio/blog-API
